# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.9.dev3+g9519c3f.d20230120'
__version_tuple__ = version_tuple = (0, 1, 9, 'dev3', 'g9519c3f.d20230120')
